### ISSUE TITLE
Build User Stories (User Journey Mapping)

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/scouts#12]
This issue is to build out all the steps for each user journey (i.e. what are all the steps in which the user will interact with our digital platform to reach the final outcome) 

## Example Template:
<img width="699" alt="Bildschirmfoto 2020-11-23 um 18 31 34" src="https://user-images.githubusercontent.com/23721486/100000875-269e2f00-2dba-11eb-9504-2113f12694e6.png">

## Presentation for more information:
https://docs.google.com/presentation/d/1JWVDThFGPnLyM5Dmw5hpN_6v87gHaj8_djWh1maTrBg/edit?usp=sharing

**Suggested delivery format**
w/c 30/11 (towards end of week as User Journeys need to be completed first) 
_Note: there's quite a few ways to deliver this in particular so this is one suggestion:_
- Initial 30-60 min session to explain user stories and do one together
- At the end of the session, we assign journeys for anyone who wants to work on these
- Deadline, end of the week to have these laid out with people welcome to add comments to suggest changes
- start of w/c 6/12, 60-90 min session to review the stories to make sure we're happy to take into wireframing -> relates https://github.com/yalla-coop/scouts/issues/15 

---

### Acceptance Criteria:
- [ ] Add each acceptance criteria as checklist like this...

**Comment by dupreesi** [comment]
list of user journeys including prioritisation: https://www.notion.so/99e1c131a0e4413dab7845197adf8d2b?v=75a5e92ac45c4c3d83e890ddd1bf7adb

here are the mapping flowcharts: https://whimsical.com/user-journey-mapping-and-tech-setup-MMyL7hs4b4hmtQyezCrXyo
