### ISSUE TITLE
Issues with Search

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/scouts#127]
**Case 1: No tool selected (using default digital tool placeholder)**:
- [ ] Search doesn't find any results
- e.g searching for "backup" w. "digital tool" (pre-selected placeholder) should at least find the Skill "I know how to keep a backup of data" and activity "How to backup data on the cloud"
- [ ] Search shows incorrect results:
- e.g. searching for "online collaboration tools" (without selecting tool) shows "I can create strong and secure passwords", but it should return only the skills / activities which include either online, collaboration or tools (or a combination of these words)
**Case 2: Only tool selected**
- [ ] Search doesn't return any results
- e.g. searching with only ... using "Microsoft Word" (no input text) should return all skills and activities with this term in either description or title
- e.g. ...using "Microsoft Excel" should find at least activity "Using Excel" / ..."Google Docs" -> "Using Google Docs"

**Comment by RamyAlshurafa** [comment]
> Search doesn't find any results
e.g searching for "backup" w. "digital tool" (pre-selected placeholder) should at least find the Skill "I know how to keep a backup of data" and activity "How to backup data on the cloud"

- [ ] so "a digital tool" includes all the tools? or it should be neutral and doesn't affect the search, so it can match on the tasks only?

> Search shows incorrect results:
e.g. searching for "online collaboration tools" (without selecting tool) shows "I can create strong and secure passwords", but it should return only the skills / activities which include either online, collaboration or tools (or a combination of these words)

- [ ] if you look at this file `server/database/dummy-data/skills.js` line 117, you will find the description contains `tool` so it matches

> Search doesn't return any results ....
- [ ] so the task input is not requried?

**Comment by thejoefriel** [comment]
Hey @RamyAlshurafa on these points:

- Yes digital tool would be neutral so it matches on the task only
- that's fine @RamyAlshurafa - it's better that we return more results than none. do you agree @dupreesi ?
- In my opinion it should either be required so they can't hit search and we show an error message saying field is required or then if optional it works like @dupreesi said

**Comment by dupreesi** [comment]
Hey @RamyAlshurafa I agree with @thejoefriel! Sorry about the point adding the incorrect results point (I should have checked the description)
