### ISSUE TITLE
Landscaping Review

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/scouts#13]
This issue is to store the final landscaping work done from the input collated across all the landscape tagged issues

_@jema28 please add to this if you think anything missing_

**Preferred delivery format**
w/c 30/11
- 60 min session
- Ideally this would be before user stories as the work on flows might inform the thought process on this
- If really needed this could be presented as a Loom video with then people invited to write comments in this issue (if they cannot attend)

---

### Acceptance Criteria:
- [ ] For us to have a better sense of what we're building at a very top UX/UI level
- [ ] Build a general consensus on the type of identity, look and feel in order to best meet our user's needs (and then use this as an inspiration as we go into thinking about user journeys and then wireframes)

The idea is we can keep building on this / come back to it over the next week so as we're going through user journeys/stories if any more inspiration comes or you see anything you like we can continue adding to the issue and we'll add that to figma

**Comment by jema28** [comment]
Hey everyone, here's the link to figma: https://www.figma.com/file/S8B4VTtiYqyaCwdU6Ib10B/Scouts-Association?node-id=22%3A62. Let me know if that's working okay!

**Comment by dupreesi** [comment]
here is an overview doc with all relevant landscaping pages: https://www.notion.so/Landscaping-9d5626b2a2314de39037e6f11dabc06a
