### ISSUE TITLE
When clicking on the dropdown options to select my answers the page would zoom in - I then had to zoom out each time

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/scouts#187]
Device: Iphone 
Browser: Safari
URL: https://scouts-staging.herokuapp.com/digital-test/3
What were you trying to do: Complete digital skills quiz
[Bug Report Reference Number](https://www.notion.so/9f4bb26bb49746f0bf128af3a20b5025?v=ac6236f5eb9a43e889e524b5ef1d4c9a): 2

**Comment by fadeomar** [comment]
can't replicate this

**Comment by fadeomar** [comment]
I think this https://github.com/ant-design/ant-design/issues/15688 is related to the bug?

**Comment by AbramovichCp** [comment]
<meta
      name="viewport"
      content="initial-scale=1, **maximum-scale=1**"
    />
works for me
