### ISSUE TITLE
Volunteer Digital Skill Assessment process and questions setup

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/scouts#19]
## Purpose of this issue:
- [ ] Thinking about assessment flow to identify users' knowledge gaps
- [ ] Create contents (e.g. questions) 
- [ ] Create scoring system to relate questions and skills
- [ ] Think about flows to link assessment methods to relevant resources (e.g. signposting to external links / using network to ask for support)

**Comment by dupreesi** [comment]
**document with initial question collection:** 
https://www.notion.so/Assessment-Framework-78ab5269ba1a4ff081621725ca77ee05

**Comment by thejoefriel** [comment]
All the questions are written here: https://whimsical.com/scout-questions-VVyrTxQ4wg3pYdWydicfCt

The question logic flow is at the top (and another format on the right) and all questions listed under skill areas with coloured lines to track where one question answers skills in multiple skill areas

**Comment by dupreesi** [comment]
@thejoefriel I added the flow do to #2
