### ISSUE TITLE
No back button on the pages where we point the user to the sign on

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/scouts#190]
Device: Windows Laptop
Browser: Chrome
URL: https://scouts-staging.herokuapp.com/login
What were you trying to do: Click back from log in page
[Bug Report Reference Number](https://www.notion.so/9f4bb26bb49746f0bf128af3a20b5025?v=ac6236f5eb9a43e889e524b5ef1d4c9a): 5

**Comment by fadeomar** [comment]
this isn't a bug as it doesn't exist in the design

**Comment by fadeomar** [comment]
add the back button to login and signup pages as I and Simon discussed
