### ISSUE TITLE
View Navbar issue (disappears)

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/scouts#194]
Between screen width sizes 991px  and 1153px neither the top mobile nav bar nor the left desktop menu appear 
Device: Windows Laptop
Browser: Chrome
URL: https://scouts-staging.herokuapp.com
What were you trying to do: View the page
[Bug Report Reference Number](https://www.notion.so/9f4bb26bb49746f0bf128af3a20b5025?v=ac6236f5eb9a43e889e524b5ef1d4c9a): 7

**Comment by RamyAlshurafa** [comment]
this pr got back the extra padding at the bottom of the pages, so @dupreesi whether to open a new issue for that or keep this issue open to fix it
