### ISSUE TITLE
Agree Data Architecture

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/scouts#27]
This issue is to discuss the data architecture aka schema
---

### Acceptance Criteria:
- [ ] Add schema overview in form of tables and relations 
- [ ] Add short explanations of table characteristics and how they related to each other

**Comment by dupreesi** [comment]
Here is the document outlining recommendations:

https://www.notion.so/Tech-Stack-External-Services-Deployment-Recommendation-341fdfd5fea0466fb073221a195934e3

**Comment by RamyAlshurafa** [comment]
[DB schema (2).pdf](https://github.com/yalla-coop/scouts/files/5829271/Untitled.2.pdf)

![Untitled](https://user-images.githubusercontent.com/34629478/104898395-4305b480-5982-11eb-95c3-981cdd083220.png)

**Comment by dupreesi** [comment]
@RamyAlshurafa just to update you 
- organisation hiding activities and skills is de-prioritised and might not be part of this sprint -> so maybe we remove related tables for now?
- organisation being able to update designs (colors/logo) is also de-prio. and might not be part of this sprint -> maybe exclude related theme in org. table?

**Comment by RamyAlshurafa** [comment]
Thanks, @dupreesi for reviewing will update them now

**Comment by RamyAlshurafa** [comment]
[DB schema (3).pdf](https://github.com/yalla-coop/scouts/files/5829376/Untitled.3.pdf)

![Untitled (1)](https://user-images.githubusercontent.com/34629478/104900113-587bde00-5984-11eb-9835-58c8ea95b395.png)
