### ISSUE TITLE
Create a series of How Might Wes 

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/scouts#3]
Get to the point of identifying the key problems we're looking to solve for our users and start thinking of these as opportunities.

**Suggested delivery format**
_w/c 23/11_
- Yalla building out initially and sharing via Mural for Scouts to review
- Scouts to add in comments and any other HMWs 
- 30min review / wrap up session 

**Mural Link**
https://app.mural.co/t/scoutsproblems3979/m/scoutsproblems3979/1606114129864/2018feee77450a5332acbb01c7bf8a81e7d72356

---

### Acceptance Criteria:
- [x] Create a series of How Might Wes 
- [x] (optional depending on where we are with problem mapping) Theme the how might wes and link with personas
- [x] Prioritise the How Might Wes

**Comment by rachelwilkinson** [comment]
Priorities suggestion - 
1. HMW identify  the gaps in user's knowledge
2. HMW make it easy for users to find appropriate resources, especially when they might not know what they're looking for
3. HMW show the user their progress
4. HMW make users feel confident to ask for support
5. HMW make it easy to update learning resources

**Comment by thejoefriel** [comment]
Priorities for me:

1. HMW we make it easy for users to quickly / share access direct links to resources or get support for specific tasks
2. HMW identify the gaps in user's knowledge
3. HMW help users get support from peers
4. HMW help DCs (or peers who know about a particular area) connect with Vs they can help
5. HMW support users to learn in a flexible way that fits around their schedules


3 & 4 overlap a lot and are dependent on this idea of p2p support / micro volunteering. However, if we go down that route then I think personally the key is empowering and enabling the DCs to reach out / connect with those needing help, as this potentially tackles the problem of confidence which I think is super important.

**Comment by dupreesi** [comment]
1. HMW help users get support from peers
2. HMW make users feel confident to ask for support
3. HMW identify the gaps in user's knowledge
4. HMW support users to learn in a flexible way that fits around their schedules
5. HMW show a user that digital skills can make some tasks easier

**Comment by jema28** [comment]
1. HMW help users without making them feel overwhelmed / this is a new obligation
3. HMW identify the gaps in user's knowledge
4. HMW help users get support from peers & HMW support users to learn in a flexible way that fits around their schedules // HMW help DCs support Vs in a flexible way that fit around their schedules 
5. HMW we make it easy for users to quickly / share access direct links to resources or get support for specific tasks

I think first making sure the site is laid out in a way that isn't overwhelming will make a big difference in them staying to look through the platform. After this, making it easy for the user figure out a few skills they're missing (known/unknown) and then get support from their peers when they have time. This also links to the DCs doing this when they have a moment. 

Lastly, users being able to find information on a specific task that they need doing (just in time).

**Comment by Stefanoandre** [comment]
1. HMW identify the gaps in user's knowledge
2. HMW support people at the right time ( stuck or with insufficient knowledge to progress )
3. HMW help people measure and improve their skills in an engaging and rewarding way ( track progress and improvements )
4. HMW boost users confidence in digital skills
5. HMW support users to learn in a flexible way that fits around their schedules

1- I think this is a good starting point because it's a proactive approach. 
2 -How best can we help people when they get stuck because they don't have sufficient knowledge to accomplish the task?
   That will include contacting peers/experts for help
5- This, in my opinion, is around customization and flexibility. Provide access to a tailored learning experience based on learning stiles and availability.
