### ISSUE TITLE
Setup grid component (column spacing layout)

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/scouts#35]
Setup common component for grid layout covering desktop / tablet / mobile for consistent width and spacing throughout the app

wireframes:  https://www.figma.com/file/9oFoQawgjFYwHi1dG77RH7/The-Scouts-Association-MVP?node-id=1004%3A31067

---

### Acceptance Criteria:
- [ ] Add common component
- [ ] Add to storybook

**Comment by thejoefriel** [comment]
This is done as part of set up so will close this
