### ISSUE TITLE
Build list of those tackling the problem

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/scouts#4]
This exercise is part of Landscaping and it helps to:

1.  **Understand the world we're building this product within (See who else is tackling the problem).**
    - This is useful because it helps us uncover:
        - The competitive landscape: who your "competitors" are and making sure we don't make something too similar
        - The trends of what this type of product looks and feels like
        - The language other similar platforms are using: what works and what doesn't
2. **Research platforms you and your users like so we can do further exploration on this**

---

### Please read below Acceptance Criteria for instructions of how to do this exercise

**Please try and comment on this issue with your feedback by the end of this week latest (27/11)**

1. - [ ] Using the template below, write out different frameworks you've researched that you think we should be aware of

**Template:**
- App/website name:
- App/website link:
- What do they do that is similar?
- What is their flow(s) like in tackling this problem?
- What is their value proposition / their key features?
- How are they received?
- What kind of language do they use? 

2. - [ ] Add as comments any digital frameworks you researched, each comment including:
- What was good?
- What wasn't so good / relevant for our problem?
- What were the common threads you discovered?

3. - [ ] What kind of language / voice / tone will best fit our user personas?

### Video explanation
https://www.loom.com/share/313f227081e2429eaecd1c2da5197587

**Comment by jema28** [comment]
### Example (1):
**App/website name:** Text

**App/website link:** Text

**What do they do that is similar?**
Text

**What is their flow(s) like to tackling this problem?**
Text

**What is their value proposition / their key features?**
Text

**How are they received?**
Text

**What kind of language do they use? What kind of language / voice / tone will best fit our user personas?**
Text

**Comment by rachelwilkinson** [comment]
PWC Digital Fitness App. To download **PwC’s Digital Fitness Assessment** app from the App Store or Google Play Store. 
You can use the code LRNALL

**Comment by rachelwilkinson** [comment]
Make it click - https://makeitclick.learnmyway.com/directory

**Comment by rachelwilkinson** [comment]
https://www.lloydsbankacademy.co.uk/#

**Comment by rachelwilkinson** [comment]
https://www.bt.com/skillsfortomorrow/home-life

**Comment by rachelwilkinson** [comment]
https://nationalcareers.service.gov.uk/find-a-course/the-skills-toolkit

**Comment by rachelwilkinson** [comment]
https://www.learnmyway.com/

**Comment by rachelwilkinson** [comment]
https://applieddigitalskills.withgoogle.com/s/en-uk/learn

**Comment by rachelwilkinson** [comment]
https://digital.wings.uk.barclays/

**Comment by rachelwilkinson** [comment]
https://www.internetmatters.org/
