### ISSUE TITLE
Set up skills and activities collection

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/scouts#49]
This will be needed to be stored eventually but we will need to agree and create a collection of skills and activities with related resources (links etc.) 

Relevant documents can be found in #2
---

### Acceptance Criteria:
- [ ] Create logic and collection

**Comment by thejoefriel** [comment]
The easiest way to set up initial data is to use a CSV to JSON converter. This means we can update the spreadsheet once we get all the links and then ahead of deployment convert. 

**EXAMPLE CSV TO USE FOR ACTIVITIES**
[activities.csv.zip](https://github.com/yalla-coop/scouts/files/5849480/activities.csv.zip)

**EXAMPLE CSV TO USE FOR LINKING ACTIVITIES TO SKILLS**
[skillActivitiesSorting copy.csv.zip](https://github.com/yalla-coop/scouts/files/5849493/skillActivitiesSorting.copy.csv.zip)

So I'd suggest using this process if we want to update big amounts of the data at once (i.e. ahead of deployment)
