### ISSUE TITLE
After finishing the quiz I am asked to enter my postcode

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/scouts#55]
- links to #54 
- before finishing the assessment quiz volunteers are prompted to enter their postcode 
- wireframes: https://www.figma.com/file/9oFoQawgjFYwHi1dG77RH7/The-Scouts-Association-MVP?node-id=1449%3A6085
---

### Acceptance Criteria:
- [x] Title and description explaining me what I need to do and linking to T&Cs
- [x] Postcode input field
- [x] CTA button (if no input given -> skip postcode)
- [x] Form validation (UK postcode)
- [x] (Bonus to add in a button to turn off the validation if overseas, see image)
- [x] prepare postcode for storage with userId
<img width="557" alt="Bildschirmfoto 2021-01-15 um 14 27 30" src="https://user-images.githubusercontent.com/23721486/104738761-d4381980-573d-11eb-90ea-9e0a900783cf.png">

**Comment by fadeomar** [comment]
we need the T&Cs link currently it's blank, will update it once its available
