### ISSUE TITLE
Build a board of visual inspiration

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/scouts#6]
In this issue we are trying to get a better sense of how the digital platform should look.

**Thinking of visual inspiration includes:**
- What apps/websites do you think your users will like the look/feel of?
- What visual language do you think suits the user personas in terms of typography, colour and graphics/illustrations. What would be attractive to them?
- Are there any brand guidelines we need to work under?
- The feedback on the MVP re looks
- Discussing accessibility

---

### Please watch below videos and check Acceptance Criteria for further instructions of how to do this exercise

**Please try and comment on this issue with your feedback by the end of this week latest (27/11)**

1. - [ ] Using the template below, write out the digital tools that you like **the look/feel** / think our users will like:

**Template:**

- App/website name:
- App/website link:
- The specific page you like and its link (and a few screenshots if possible!) and a description of why you and our user personas would like the typography, colour, graphics or illustrations etc.

2. - [ ] Please list in the comments below any particular feedback on the current MVP you think is important to consider
3. - [ ] List links / documents for any brand guidelines we need to follow
4. - [ ] We need to agree the level of accessibility (we're assuming AAA, https://www.w3.org/WAI/WCAG2AAA-Conformance ?)

### Video explanations
**Part 1**
https://www.loom.com/share/5d8bf929269c4247819c04801735b12f

**Part 2**
https://www.loom.com/share/f4280158bfd643898cbbabf921b763a0

**Comment by jema28** [comment]
### Example:

**App/website name:** _TEXT_

**App/website link:** _TEXT_

**The specific page you like and its link (and a few screenshots if possible!) and a description of why you and our user personas would like the typography, colour, graphics or illustrations etc.**
_TEXT_
