### ISSUE TITLE
I can find help for a specific task (volunteer)

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/scouts#65]
- search functionality for mobile and desktop
- relates #66 
- wireframes: https://www.figma.com/file/9oFoQawgjFYwHi1dG77RH7/The-Scouts-Association-MVP?node-id=1449%3A5791
- reach out to @RamyAlshurafa to get advice for search logic
---

### Acceptance Criteria:
- [ ] Search section w. title, natural language search (text combination of search inputs) and search button (→ sends query to backend and redirects to results page)
- [ ] Most popular tasks section w. title and list of 5 clickable titles
- [ ] Search functionality using combination of key word search (task) and dropdown (tool) with postgresql search query feature

**Comment by RamyAlshurafa** [comment]
Hey @dupreesi can elaborate more about what fields to query on the search, i assume we need to search in the skill (title, description, tasks?), also do we need to get the skills that contain activity that matches the search? if so, what the fields in activity?

**Comment by dupreesi** [comment]
hey @RamyAlshurafa, I think we take all the search inputs and start a searching in both tables (Skills and Activities) for fields Title and Description. 
Does that work?

**Comment by RamyAlshurafa** [comment]
thanks @dupreesi , that makes sense, but just to make sure, the results would be the skills, right?
also what are the options for the dropdown?

**Comment by dupreesi** [comment]
so the results should show both Skills and Activities. Anything that matches the search inputs. The options for dropdowns would need to be hard coded and be a collection of tools we are including into our skills / activities. Examples are Word, Excel, Zoom etc. This would then be added to the search as words.. Are you ok to create a basic collection for now and we will get Scouts to send over a final collection asap (its already on their list of tasks)?

**Comment by RamyAlshurafa** [comment]
ok thanks @dupreesi 
all make sense
