### ISSUE TITLE
Build Crazy 8s for potential solutions and Prioritise 

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/scouts#7]
Crazy 8’s is a core Design Sprint method. It is a fast sketching exercise that challenges people to sketch eight distinct ideas in eight minutes. The goal is to push beyond your first idea, frequently the least innovative, and to generate a wide variety of solutions to your challenge. 

## suggested format
- Initial 60 min session to introduce the concept and try out in a group -> Date TBA @Tommortimerhart to organise the session
- Any further solutions not covered can get picked up remotely

## Mural Board
https://app.mural.co/t/scoutsproblems3979/m/scoutsproblems3979/1606465095624/0760f686d9c53e6d333a6173d8bd784ae720e677

---

### Acceptance Criteria:
- [ ] Create crazy 8s for each of the HMWs
    - Grab a HMW (one of the post it notes) from the top of the mural board and drag to one of the available blue boards
    - Write your name where it says name
    - Enter your ideas (if you are including text, just double click where it says 'Idea here' until the words are highlighted then you can type 👍 
- [ ] Each person votes for their preferred solution
    - Read through the other crazy 8s
    - Add any questions or thoughts you have as a comment (or comments)
    - Feel free to add more solutions if you like! 
    - Try and add a pink dot to your favourite solution

**Deadline: Tues lunchtime so we have the basis for our user journeys**

**Comment by Tommortimerhart** [comment]
Thanks @dupreesi - invite dispatched.
